# Generated by Django 4.2.16 on 2025-03-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='therapy',
            field=models.CharField(blank=True, choices=[('Insulin', 'Insulin'), ('Tablets', 'Tablets')], max_length=10, null=True),
        ),
    ]
