# Generated by Django 4.2.16 on 2025-04-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_gender_alter_profile_therapy'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_calorie_goal',
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=7),
        ),
    ]
