# Generated by Django 4.2.16 on 2025-04-28 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_daily_calorie_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='daily_calorie_goal',
        ),
    ]
