# Generated by Django 5.1.6 on 2025-02-06 20:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image_url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                ("meal_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                            ("snack", "Snack"),
                        ],
                        default="snack",
                        max_length=10,
                    ),
                ),
                ("portion_size", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "calories",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
                ),
                (
                    "fat",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
                ),
                (
                    "carbohydrates",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
                ),
                (
                    "protein",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
                ),
                (
                    "sugars",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("time", models.TimeField(default=django.utils.timezone.now)),
                (
                    "food_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="diet.food"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
