# Generated by Django 4.2.16 on 2025-02-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food",
            name="image_url",
        ),
        migrations.AddField(
            model_name="food",
            name="calories",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="food",
            name="carbohydrates",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="food",
            name="fat",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="food",
            name="portion_size",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
        ),
        migrations.AddField(
            model_name="food",
            name="protein",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="food",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
