# Generated by Django 4.2.16 on 2025-02-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0003_rename_portion_size_food_serving_size_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="food",
            old_name="serving_size",
            new_name="portion_size",
        ),
        migrations.AddField(
            model_name="food",
            name="carbohydrates",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="food",
            name="fat",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="food",
            name="protein",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
