# Generated by Django 4.2.16 on 2025-02-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0005_food_meal_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="calories_consumed",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name="meal",
            name="calories_remaining",
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=7),
        ),
        migrations.AddField(
            model_name="meal",
            name="daily_calorie_goal",
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=7),
        ),
    ]
