# Generated by Django 4.2.16 on 2025-02-16 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0006_meal_calories_consumed_meal_calories_remaining_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food",
            name="meal_type",
        ),
    ]
