# Generated by Django 4.2.16 on 2025-04-28 23:23

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diet', '0008_stephistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calorie_Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_calorie_goal', models.DecimalField(decimal_places=2, default=Decimal('2000.00'), max_digits=7)),
                ('daily_protein_goal', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('daily_carb_goal', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('daily_fat_goal', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calorie_goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
