# Generated by Django 4.2.16 on 2025-04-28 23:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diet', '0009_calorie_goals'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calorie_Goals',
            new_name='CalorieGoals',
        ),
    ]
