# Generated by Django 4.2.16 on 2025-04-29 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diet', '0010_rename_calorie_goals_caloriegoals'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('daily_calorie_goal', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_calories_consumed', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_protein', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_carbs', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_fats', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_sugars', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_steps', models.IntegerField(default=0)),
                ('calories_burned_by_steps', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('calories_remaining', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('net_calories', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.RemoveField(
            model_name='meal',
            name='calories_consumed',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='calories_remaining',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='daily_calorie_goal',
        ),
        migrations.DeleteModel(
            name='CalorieGoals',
        ),
    ]
