# Generated by Django 4.2.16 on 2025-04-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0012_remove_dailysummary_daily_calorie_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysummary',
            name='calories_burned_by_steps',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='calories_remaining',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='net_calories',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='total_calories_consumed',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='total_carbs',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='total_fats',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='total_protein',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='total_sugars',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
    ]
