# Generated by Django 4.2.16 on 2025-04-29 10:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0013_alter_dailysummary_calories_burned_by_steps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caloriegoals',
            name='daily_calorie_goal',
            field=models.DecimalField(decimal_places=0, default=Decimal('2000.00'), max_digits=7),
        ),
        migrations.AlterField(
            model_name='caloriegoals',
            name='daily_carb_goal',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='caloriegoals',
            name='daily_fat_goal',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='caloriegoals',
            name='daily_protein_goal',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True),
        ),
    ]
