# Generated by Django 4.2.16 on 2025-04-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0014_alter_caloriegoals_daily_calorie_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='sugars',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
