# Generated by Django 4.2.16 on 2025-05-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0015_food_sugars'),
    ]

    operations = [
        migrations.AddField(
            model_name='stephistory',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=6),
            preserve_default=False,
        ),
    ]
