# Generated by Django 4.2.16 on 2025-06-10 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_passwordresetotp_created_at_and_more'),
        ('diet', '0016_stephistory_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CumulativeSteps',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('last_cumulative_value', models.IntegerField(default=0)),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='stephistory',
            name='cumulative_steps',
            field=models.IntegerField(default=0),
        ),
    ]
