# Generated by Django 4.2.16 on 2025-06-10 14:58

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diet', '0017_cumulativesteps_stephistory_cumulative_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='cumulativesteps',
            name='baseline_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cumulativesteps',
            name='current_day_baseline',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stephistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='stephistory',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='stephistory',
            index=models.Index(fields=['user', 'date'], name='diet_stephi_user_id_658035_idx'),
        ),
    ]
