# Generated by Django 4.2.16 on 2025-06-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0018_cumulativesteps_baseline_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stephistory',
            name='calories_burned',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
