# Generated by Django 4.2.16 on 2025-06-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0019_alter_stephistory_calories_burned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cumulativesteps',
            name='last_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stephistory',
            name='date',
            field=models.DateField(),
        ),
    ]
