# Generated by Django 4.2.16 on 2025-03-06 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FootUlcer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="media/uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("classification_result", models.CharField(max_length=50)),
                ("confidence", models.FloatField()),
                (
                    "segmented_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/uploads/segmented/"
                    ),
                ),
                ("ulcer_area", models.FloatField(blank=True, null=True)),
                ("last_area", models.FloatField(blank=True, null=True)),
                ("area_difference", models.FloatField(blank=True, null=True)),
                (
                    "improvement_message",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="footcare",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
