# Generated by Django 4.2.16 on 2025-03-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("footcare", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footulcer",
            name="image",
            field=models.ImageField(upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="footulcer",
            name="segmented_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/segmented/"
            ),
        ),
    ]
