# Generated by Django 4.2.16 on 2025-05-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footcare', '0002_alter_footulcer_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footulcer',
            name='region',
            field=models.CharField(default='Foot Ulcer', max_length=50),
        ),
    ]
