# Generated by Django 4.2.16 on 2025-05-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footcare', '0003_footulcer_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footulcer',
            name='region',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
