# Generated by Django 4.2.16 on 2025-05-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footcare', '0005_alter_footulcer_classification_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footulcer',
            name='region',
            field=models.CharField(max_length=50),
        ),
    ]
