# Generated by Django 5.1.6 on 2025-02-06 20:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medication_name",
                    models.CharField(
                        help_text="Generic name of the medication", max_length=100
                    ),
                ),
                (
                    "route_of_administration",
                    models.CharField(
                        choices=[
                            ("oral", "Orally"),
                            ("parentral/im", "Intra-muscular"),
                            ("parentral/iv", "Intravenous"),
                            ("parentral/sc", "Subcutaneous"),
                        ],
                        default="oral",
                        max_length=50,
                    ),
                ),
                (
                    "dosage_form",
                    models.CharField(
                        choices=[
                            ("tablet", "Tablet"),
                            ("capsule", "Capsule"),
                            ("syrup", "Syrup"),
                            ("injectable", "Injectable"),
                        ],
                        default="syrup",
                        max_length=50,
                    ),
                ),
                (
                    "dosage_unit_of_measure",
                    models.CharField(
                        choices=[
                            ("tablet", "Tablet"),
                            ("capsule", "Capsule"),
                            ("gravimetric/mg", "Milligram (mg)"),
                            ("volumetric/ml", "Milliliter/ml"),
                        ],
                        default="tablet",
                        max_length=50,
                    ),
                ),
                ("dosage_quantity_of_units_per_time", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "interaction_warning",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "equally_distributed_regimen",
                    models.BooleanField(default=True, null=True),
                ),
                ("dosage_frequency", models.PositiveIntegerField()),
                (
                    "periodic_interval",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                (
                    "first_time_of_intake",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_chronic_or_acute", models.BooleanField(default=False, null=True)),
                ("stopped_by_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
