# Generated by Django 4.2.16 on 2025-02-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medication",
            name="failed_interactions",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
