# Generated by Django 4.2.16 on 2025-02-12 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medication", "0002_medication_failed_interactions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medication",
            name="failed_interactions",
        ),
    ]
