# Generated by Django 4.2.16 on 2025-02-18 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medication", "0003_remove_medication_failed_interactions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medication",
            name="stopped_by_datetime",
        ),
    ]
