# Generated by Django 4.2.16 on 2025-02-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medication", "0004_remove_medication_stopped_by_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="medication",
            name="stopped_by_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
