# Generated by Django 4.2.16 on 2025-02-26 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0002_device'),
        ('medication', '0005_medication_stopped_by_datetime'),
    ]

    operations = [
    ]
