# Generated by Django 4.2.16 on 2025-02-26 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0006_merge_0002_device_0005_medication_stopped_by_datetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
