# Generated by Django 4.2.16 on 2025-03-18 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0007_delete_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='is_chronic_or_acute',
        ),
    ]
