# Generated by Django 4.2.16 on 2025-04-10 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGlucose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_glucose', models.FloatField()),
                ('time_of_measurement', models.CharField(choices=[('Pre-Breakfast', 'Pre-Breakfast'), ('Post-Breakfast', 'Post-Breakfast'), ('Pre-Lunch', 'Pre-Lunch'), ('Post-Lunch', 'Post-Lunch'), ('Pre-Dinner', 'Pre-Dinner'), ('Post-Dinner', 'Post-Dinner'), ('Random', 'Random')], max_length=20)),
                ('severity', models.CharField(max_length=50)),
                ('predicted_glucose', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
