# Generated by Django 4.2.16 on 2025-06-23 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diabetis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodglucose',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
